version: "3.7"

services:
  db:
    container_name: tell-me-db
    build: ./mariadb
    image: custom-mariadb
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=LARAVELDB
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      #- ./mariadb/conf:/etc/mysql
      #- ./mariadb/log:/var/log/mysql
    networks:
      - laravel

  laravel:
    # docker-compose scale 설정시 continer_name 주석
    container_name: tell-me-app
    # build: .
    # image: custom-laravel
    image: papion93/docker-laravel:0.2
    restart: always
    volumes:
      - ./laravel-project:/var/www/html
    networks:
      - laravel

  nginx:
    container_name: tell-me-proxy
    image: nginx:latest
    ports:
      - 10080:80
      - 443:443
    restart: always
    volumes:
      - ./laravel-project:/var/www/html
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel

networks:
  laravel:
    external: true
