version: "3.7"

services:
  laravel:
    # docker-compose scale 설정시 continer_name 주석
    container_name: tell-me-app
    build: .
    image: custom-laravel
    restart: unless-stopped
    volumes:
      - ./laravel-project:/var/www/html
    networks:
      - laravel

  nginx:
    container_name: tell-me-proxy
    # image: nginx:latest
    build: ./proxy
    ports:
      - 10080:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./laravel-project:/var/www/html
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel

networks:
  laravel:
    external: true
